### PR TITLE
fix V4 race

### PR DESCRIPTION
**Pull request by robmurtha**
V4 causes a data race on generator.err

### CODE REVIEW

**Comment by twinj** [comment]
Thanks for contributing. 

Are you able to to provide me with code which causes the problem? 

I was considering ripping out the error handling in the generator as it doesn't have much value. There has been a bit of debate about how to proceed when there is an error in the random number generator in other libraries, so I thought I'd tackle the issue.

Retrieval of the error remains a problem in your proposed change, which occurs after unlocking the generator and then when .Error() is called on the generator. If NewV4 is run in several go routines you cannot be sure which error you are getting and if it matters. So in saying that this library does not currently handle that situation properly.  Most libraries ignore the issue.

I'm open to suggestions.

**Comment by robmurtha** [comment]
Sure, I kept it small because I also agree that the usage of err is not clear and mutation occurs in unexpected places. Seems like the only reliable way to deal with this is to either have MustNewV4 and panic or provide another NewV4WithError func that returns the error. I just tried commenting out the o.err = nil in Generator.Error() and all the tests still pass.

The race condition showed up using the -race flag with some data generation tests that use multiple go routines.

**Comment by robmurtha** [comment]
I added a concurrent test. If you think the error should be sticky then we could just add setError func and once it is not nil just ignore any new errors. I'm not sure what circumstances will produce an error or if you can recover by creating a new generator. If these changes are ok I can squash if you like.

**Comment by robmurtha** [comment]
@twinj thoughts?

**Comment by twinj** [comment]
It's safe to remove the .err code. It's just not needed. The HandleError function gives the user of the library the opportunity to handle the error in a way that suits their need. The default being to panic. This will be extremely rare in any case. 

I have already added a NewV4Safe() uuid, error in a branch, for those that just want to check the error. Which is probably the best way to handle it.  That branch will not be merged here however. I'd like the function to have the same name at least.  

NewV4 will have to check for nil but with a decent handleError method or some fallback way to ensure quality random bytes can be retrieved this could probably change to a value rather than a pointer. The purpose of the error handler was an attempt to remove the redundancy of checking for an error or nil on every single call. 

At this stage the generator isn't completely designed to be safe in all areas of use with several go routines. It is something that needs to be addressed and properly tested. 

Unfortunately the branch has major changes in it to improve performance. I have moved the repo. so new adopters can use the newer library. I just haven't finished those changes as yet.

**Comment by twinj** [comment]
I will be finishing this library in the coming weeks. Finally got a break from work.

**Pull request closed without merging**
